version: '3'

services:
  database:
    image: mariadb
    environment:
        - MYSQL_DATABASE=apikit_db
        - MYSQL_USER=apikit_user
        - MYSQL_PASSWORD=apikit_password
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
        - ./data/db:/var/lib/mysql
    ports:
        - 6336:3306
    command: 
        --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password